config/routes.rb
Rails.application.routes.draw do

  root to: 'site#home'

  devise_for :users
  get 'site/about'
  get 'site/home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :activities
end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :activities
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_activity, only: [:show, :edit, :update, :destroy]

  # GET /activities
  # GET /activities.json
  def index
    @activities = Activity.all
  end

  # GET /activities/1
  # GET /activities/1.json
  def show
  end

  # GET /activities/new
  def new
    @activity = current_user.activities.build
  end

  # GET /activities/1/edit
  def edit
  end

  # POST /activities
  # POST /activities.json
  def create
    @activity = current_user.activities.build(activity_params)

    respond_to do |format|
      if @activity.save
        format.html { redirect_to @activity, notice: 'Activity was successfully created.' }
        format.json { render :show, status: :created, location: @activity }
      else
        format.html { render :new }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activities/1
  # PATCH/PUT /activities/1.json
  def update
    respond_to do |format|
      if @activity.update(activity_params)
        format.html { redirect_to @activity, notice: 'Activity was successfully updated.' }
        format.json { render :show, status: :ok, location: @activity }
      else
        format.html { render :edit }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @activity.destroy
    respond_to do |format|
      format.html { redirect_to activities_url, notice: 'Activity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = Activity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def activity_params
      params.fetch(:activity, {}).permit(:name, :date, :duration, :note)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def after_sign_in_path_for(resource)
    activities_path
  end

  def after_sign_out_path_for(resource_or_scope)
    request.referrer
  end

end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def about
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/activities/_form.html.erb
<%= form_with(model: activity, local: true) do |form| %>
  <% if activity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
      <% activity.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="actions">
	<%= form.label :name %>
	<%= form.select :name, ["1 - Swimming", "2 - Running", "3 - Hiking", "4 - Walking", "5 - Skating", "6 - Cycling", "7 - Mountain Biking", "8 - Snowboarding", "9 - Downhill Skiing", "10 - Eliptical", "11 - Strength Training", "12 - Circuit Training", "13 - Core Strength", "14 - Arc Trainer", "15 - Rowing", "16 - Nordic Walking", "18 - XC Skiing"] %>
	|
	<%= form.label :date %>
	<%= form.date_field :date %>
	|
	<%= form.label :duration %>
	<%= form.text_field :duration %>
	|
	<%= form.label :note %>
	<%= form.text_field :note %>

	<%= form.submit %>
  </div>

<% end %>

app/views/activities/edit.html.erb
<h1>Editing Activity</h1>

<%= render 'form', activity: @activity %>

<%= link_to 'Show', @activity %> |
<%= link_to 'Back', activities_path %>

app/views/activities/index.html.erb
<h1>Activities</h1>

<table>
  <thead>
    <tr>
      <th>Activity</th>
      <th>User</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @activities.each do |activity| %>
    <tr>
      <td><%= activity.name %></td>
      <td><%= activity.user.email %></td>
      <td><%= activity.date %></td>
      <td><%= link_to 'Show', activity %></td>
      <% if activity.user == current_user %>
      <td><%= link_to 'Edit', edit_activity_path(activity) %></td>
      <td><%= link_to 'Destroy', activity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tr>
    <% end %>
  </tbody>
</table>

<br>


<%= link_to 'New Activity', new_activity_path %>

app/views/activities/new.html.erb
<h1>New Activity</h1>

<%= render 'form', activity: @activity %>

<%= link_to 'Back', activities_path %>

app/views/activities/show.html.erb
<h2><%= @activity.name %></h2>

<p><b>Date: </b><%= @activity.date %></p>
<p><b>Duration: </b><%= @activity.duration %></p>
<p><b>Note: </b><%= @activity.note %></p>

<%= link_to 'Edit', edit_activity_path(@activity) %> |
<%= link_to 'Back', activities_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Moveandgroove</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

</head>

<nav class="navbar fixed-top navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/site/home">Move and Groove</a>
    </div>
    <ul class="nav navbar-nav">
      <li><a href="/site/about">About</a></li>
      <li><%=link_to "Activity", :activities %></li>
    </ul>
    <p class="navbar-text"><% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong>.
      <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
      <% else %>
      <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
      <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
      <% end %>
    </p>
  </div>
</nav>

<body>
  <div class= container>
    <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <div class="jumbotron">
      <%= yield %>
    </div>
  </div>
</body>

<footer class="page-footer font-small mdb-color pt-4">
  <div class="container text-center text-md-left">
    <div class="row text-center text-md-left mt-3 pb-3">
      <hr class="w-100 clearfix d-md-none">
      <div class="col-md-4 col-lg-4 col-xl-4 mx-auto mt-3">
        <h6 class="text-uppercase mb-4 font-weight-bold">Move and Groove</h6>
        <p>Fitness tracking site. Physical activity is important for health.
          <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> for free!</p>
          <p>Please contact us for suggestions about new activities.</p>
        </div>
        <div class="col-md-4 col-lg-4 col-xl-4 mx-auto mt-3">
          <h6 class="text-uppercase mb-4 font-weight-bold">Homepage Links</h6>
          <p><a href="/site/home">Home</a></p>
          <p><a href="/site/about">About</a></p>
          <p><%=link_to "Activity", :activities %></p>
        </div>
        <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mt-3">
          <h6 class="text-uppercase mb-4 font-weight-bold">Contact</h6>
          <p><i class="fa fa-home mr-3"></i> New York, NY 10012, US</p>
          <p><i class="fa fa-envelope mr-3"></i> info@gmail.com</p>
          <p><i class="fa fa-phone mr-3"></i> + 01 234 567 88</p>
          <p><i class="fa fa-print mr-3"></i> + 01 234 567 89</p>
        </footer>
        </html>

app/views/site/about.html.erb
<h1 class="display-3" align="center">Move and Groove</h1>
<h3>The Importance Of Physical Fitness</h3>
<p>A person who is fit is capable of living life to its fullest extent. Physical and mental fitness play very important roles in your lives and people who are both, physically and mentally fit are less prone to medical conditions as well.</p>
<h3>What is Fitness?</h3>
<p>Fitness does not only refer to being physically fit, but also refers to a person’s mental state as well. If a person is physically fit, but mentally unwell or troubled, he or she will not be able to function optimally. Mental fitness can only be achieved if your body is functioning well. You can help relax your own mind and eliminate stresses by exercising regularly and eating right.</p>
<h3>Why is it Important to Be Physically Fit?</h3>
<p>People who are physically fit are also healthier, are able to maintain their most optimum weight, and are also not prone to cardiac and other health problems. In order to maintain a relaxed state of mind, a person should be physically active. A person who is fit both physically and mentally is strong enough to face the ups and downs of life, and is not affected by drastic changes if they take place.</p>


<h2>Activities:</h2>
<table>
	<tr>
		<td>1</td>
		<td>Swimming</td>
		<td>Swimming is an individual or team sport that requires the use of one's arms and legs to move the body through water. The sport takes place in pools or open water. </td>
	</tr>
	<tr>
		<td>2</td>
		<td>Running</td>
		<td>Running is a method of terrestrial locomotion allowing humans and other animals to move rapidly on foot. Running is a type of gait characterized by an aerial phase in which all feet are above the ground.</td>
	</tr>
	<tr>
		<td>3</td>
		<td>Hiking</td>
		<td>Hiking is the preferred term, in Canada and the United States, for a long, vigorous walk, usually on trails, in the countryside, while the word walking is used for shorter, particularly urban walks.</td>
	</tr>
	<tr>
		<td>4</td>
		<td>Walking</td>
		<td>Walking is one of the main gaits of locomotion among legged animals. Walking is typically slower than running and other gaits. Walking is defined by an 'inverted pendulum' gait in which the body vaults over the stiff limb or limbs with each step.</td>
	</tr>
	<tr>
		<td>5</td>
		<td>Skating</td>
		<td>Roller skating is the traveling on surfaces with roller skates. It is a form of recreational activity as well as a sport, and can also be a form of transportation. Skates generally come in three basic varieties: quad roller skates, inline skates or blades and tri-skates, though some have experimented with a single-wheeled "quintessence skate" or other variations on the basic skate design. </td>
	</tr>
	<tr>
		<td>6</td>
		<td>Cycling</td>
		<td>Cycling, also called bicycling or biking, is the use of bicycles for transport, recreation, exercise or sport. People engaged in cycling are referred to as "cyclists", "bikers", or less commonly, as "bicyclists". </td>
	</tr>
	<tr>
		<td>7</td>
		<td>Mountain Biking</td>
		<td>A mountain bike or mountain bicycle is a bicycle designed for off-road cycling. Mountain bikes share similarities with other bicycles, but incorporate features designed to enhance durability and performance in rough terrain. </td>
	</tr>
	<tr>
		<td>8</td>
		<td>Snowboarding</td>
		<td>Snowboarding is a recreational activity and Olympic and Paralympic sport that involves descending a snow-covered slope while standing on a snowboard attached to a rider's feet. The development of snowboarding was inspired by skateboarding, sledding, surfing and skiing.</td>
	</tr>
	<tr>
		<td>9</td>
		<td>Downhill Skiing</td>
		<td>Skiing can be a means of transport, a recreational activity or a competitive winter sport in which the participant uses skis to glide on snow. Many types of competitive skiing events are recognized by the International Olympic Committee, and the International Ski Federation.</td>
	</tr>
	<tr>
		<td>10</td>
		<td>Eliptical</td>
		<td>An elliptical trainer or cross-trainer (also called an X-trainer) is a stationary exercise machine used to simulate stair climbing, walking, or running without causing excessive pressure to the joints, hence decreasing the risk of impact injuries. For this reason, people with some injuries can use an elliptical to stay fit, as the low impact affects them little. Elliptical trainers offer a non-impact cardiovascular workout that can vary from light to high intensity based on the speed of the exercise and the resistance preference set by the user.</td>
	</tr>
	<tr>
		<td>11</td>
		<td>Strength Training</td>
		<td>Weight training is a common type of strength training for developing the strength and size of skeletal muscles. It utilizes the force of gravity in the form of weighted bars, dumbbells or weight stacks in order to oppose the force generated by muscle through concentric or eccentric contraction.</td>
	</tr>
	<tr>
		<td>12</td>
		<td>Circuit Training</td>
		<td>Circuit training is a form of body conditioning or endurance training or resistance training using high-intensity. It targets strength building or muscular endurance. An exercise "circuit" is one completion of all prescribed exercises in the program.</td>
	</tr>
	<tr>
		<td>13</td>
		<td>Core Strength</td>
		<td>Core-strength exercises strengthen your core muscles, including your abdominal muscles, back muscles and the muscles around the pelvis. Strong core muscles make it easier to do many physical activities. You can do core-strength exercises on a carpeted floor or mat.</td>
	</tr>
	<tr>
		<td>14</td>
		<td>Arc Trainer</td>
		<td>The Arc Trainer is a stationary, non-impact exercise machine, and is a registered trademark of Cybex International, Inc. The Arc Trainer is manufactured in Owatonna MN.</td>
	</tr>
	<tr>
		<td>15</td>
		<td>Rowing</td>
		<td>Rowing, often referred to as crew in the United States, is a sport whose origins reach back to Ancient Egyptian times. It involves propelling a boat on water using oars. By pushing against the water with an oar, a force is generated to move the boat.</td>
	</tr>
	<tr>
		<td>16</td>
		<td>Nordic Walking</td>
		<td>Nordic walking is a total body version of walking that can be enjoyed both by non-athletes as a health-promoting physical activity, and by athletes as a sport. The activity is performed with specially designed walking poles similar to ski poles.</td>
	</tr>
	<tr>
		<td>17</td>
		<td>XC Skiing</td>
		<td>Cross-country skiing is a form of skiing where skiers rely on their own locomotion to move across snow-covered terrain, rather than using ski lifts or other forms of assistance. Cross-country skiing is widely practiced as a sport and recreational activity; however, some still use it as a means of transportation.</td>
	</tr>
</table>
<hr class="my-4">
<a class="btn btn-primary btn-lg" href="/activities" role="button">Activities</a>

app/views/site/home.html.erb
<h1 align="center">Move and Groove</h1>

<div class="videoWrapper">
<iframe align="center" width="935" height="526" src="https://www.youtube.com/embed/SX7fNNXOOTo" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div>

<hr class="my-4">
<p>On this webpage you can see the workout from other people and you can track your workouts.</p>
<p class="lead">
	<a class="btn btn-primary btn-lg" href="/site/about" role="button">Learn more</a>
</p>